/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2025-10-12 16:43:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.owner;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.vehicle.OwnerBookingsServlet.BookingRow;

public final class bookings_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.vehicle.OwnerBookingsServlet.BookingRow");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"ISO-8859-1\">\n");
      out.write("  <title>Owner Bookings</title>\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");

  response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
  if (session.getAttribute("owner_id") == null) {
    response.sendRedirect(request.getContextPath() + "/owner/login");
    return;
  }
  List<BookingRow> bookings = (List<BookingRow>) request.getAttribute("bookings");

      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\n");
      out.write("  <div class=\"container-fluid\">\n");
      out.write("    <a class=\"navbar-brand\" href=\"");
      out.print( request.getContextPath() );
      out.write("/owner/dashboard\">MotorHub Owner</a>\n");
      out.write("    <div class=\"collapse navbar-collapse\">\n");
      out.write("      <ul class=\"navbar-nav me-auto\">\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/owner/dashboard\">Dashboard</a></li>\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/owner/vehicles\">My Vehicles</a></li>\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link active\" href=\"");
      out.print( request.getContextPath() );
      out.write("/owner/bookings\">Bookings</a></li>\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/owner/revenue\">Revenue</a></li>\n");
      out.write("      </ul>\n");
      out.write("      <a class=\"btn btn-outline-light\" href=\"");
      out.print( request.getContextPath() );
      out.write("/owner/logout\">Logout</a>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"container py-4\">\n");
      out.write("  <h3 class=\"mb-3\">Bookings</h3>\n");
      out.write("\n");
      out.write("  <div class=\"table-responsive shadow-sm\">\n");
      out.write("    <table class=\"table table-hover align-middle\">\n");
      out.write("      <thead class=\"table-light\">\n");
      out.write("        <tr>\n");
      out.write("          <th>Photo</th>\n");
      out.write("          <th>Vehicle</th>\n");
      out.write("          <th>Dates</th>\n");
      out.write("          <th>Total</th>\n");
      out.write("          <th>User</th>\n");
      out.write("          <th>Status</th>\n");
      out.write("          <th class=\"text-end\">Actions</th>\n");
      out.write("        </tr>\n");
      out.write("      </thead>\n");
      out.write("      <tbody>\n");
      out.write("      ");
 if (bookings != null) {
           for (BookingRow b : bookings) { 
      out.write("\n");
      out.write("        <tr>\n");
      out.write("          <td style=\"width:140px\">\n");
      out.write("            ");
 if (b.imageUrl != null) { 
      out.write("\n");
      out.write("              <img src=\"");
      out.print( b.imageUrl );
      out.write("\" class=\"img-thumbnail\" style=\"max-height:80px;\"/>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("          </td>\n");
      out.write("          <td>\n");
      out.write("            <div class=\"fw-semibold\">");
      out.print( b.vehicleName );
      out.write("</div>\n");
      out.write("            <div class=\"text-muted small\">");
      out.print( b.vehicleType );
      out.write(" â¢ ID #");
      out.print( b.vehicleId );
      out.write("</div>\n");
      out.write("          </td>\n");
      out.write("          <td>");
      out.print( b.startDate );
      out.write(" â ");
      out.print( b.endDate );
      out.write("</td>\n");
      out.write("          <td>â¹ ");
      out.print( String.format("%.2f", b.totalAmount) );
      out.write("</td>\n");
      out.write("          <td>#");
      out.print( b.userId );
      out.write("</td>\n");
      out.write("          <td>\n");
      out.write("            <span class=\"badge ");
      out.print( "Approved".equals(b.status)?"bg-success":("Pending".equals(b.status)?"bg-warning text-dark":("Rejected".equals(b.status)?"bg-danger":"bg-secondary")) );
      out.write('"');
      out.write('>');
      out.print( b.status );
      out.write("</span>\n");
      out.write("          </td>\n");
      out.write("          <td class=\"text-end\">\n");
      out.write("            <form action=\"");
      out.print( request.getContextPath() );
      out.write("/owner/bookings/action\" method=\"POST\" class=\"d-inline\">\n");
      out.write("              <input type=\"hidden\" name=\"booking_id\" value=\"");
      out.print( b.bookingId );
      out.write("\">\n");
      out.write("              <input type=\"hidden\" name=\"vehicle_id\" value=\"");
      out.print( b.vehicleId );
      out.write("\">\n");
      out.write("              <button name=\"action\" value=\"approve\" class=\"btn btn-sm btn-outline-success\" ");
      out.print( !"Pending".equals(b.status) ? "disabled" : "" );
      out.write(">Approve</button>\n");
      out.write("            </form>\n");
      out.write("            <form action=\"");
      out.print( request.getContextPath() );
      out.write("/owner/bookings/action\" method=\"POST\" class=\"d-inline\">\n");
      out.write("              <input type=\"hidden\" name=\"booking_id\" value=\"");
      out.print( b.bookingId );
      out.write("\">\n");
      out.write("              <input type=\"hidden\" name=\"vehicle_id\" value=\"");
      out.print( b.vehicleId );
      out.write("\">\n");
      out.write("              <button name=\"action\" value=\"reject\" class=\"btn btn-sm btn-outline-danger\" ");
      out.print( !"Pending".equals(b.status) ? "disabled" : "" );
      out.write(">Reject</button>\n");
      out.write("            </form>\n");
      out.write("            <form action=\"");
      out.print( request.getContextPath() );
      out.write("/owner/bookings/action\" method=\"POST\" class=\"d-inline\">\n");
      out.write("              <input type=\"hidden\" name=\"booking_id\" value=\"");
      out.print( b.bookingId );
      out.write("\">\n");
      out.write("              <input type=\"hidden\" name=\"vehicle_id\" value=\"");
      out.print( b.vehicleId );
      out.write("\">\n");
      out.write("              <button name=\"action\" value=\"complete\" class=\"btn btn-sm btn-outline-primary\" ");
      out.print( !"Approved".equals(b.status) ? "disabled" : "" );
      out.write(">Complete</button>\n");
      out.write("            </form>\n");
      out.write("          </td>\n");
      out.write("        </tr>\n");
      out.write("      ");
 } } 
      out.write("\n");
      out.write("      </tbody>\n");
      out.write("    </table>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
