/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2025-10-12 16:43:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.owner;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"ISO-8859-1\">\n");
      out.write("  <title>Owner Dashboard</title>\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("  <style>\n");
      out.write("    body { background-color: #f7f9fb; }\n");
      out.write("    .brand { font-weight: 700; letter-spacing: .5px; }\n");
      out.write("    .stat-card { border: 0; border-radius: 1rem; box-shadow: 0 8px 24px rgba(0,0,0,.08); }\n");
      out.write("    .stat-value { font-size: 2.2rem; font-weight: 700; }\n");
      out.write("    .nav-link.active { font-weight: 600; }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");

  response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
  if (session.getAttribute("owner_id") == null) {
    response.sendRedirect(request.getContextPath() + "/owner/login");
    return;
  }
  String ownerName = (String) session.getAttribute("owner_name");
  long totalVehicles = (request.getAttribute("totalVehicles") != null) ? (Long) request.getAttribute("totalVehicles") : 0L;
  long pendingBookings = (request.getAttribute("pendingBookings") != null) ? (Long) request.getAttribute("pendingBookings") : 0L;
  long approvedBookings = (request.getAttribute("approvedBookings") != null) ? (Long) request.getAttribute("approvedBookings") : 0L;
  double totalRevenue = (request.getAttribute("totalRevenue") != null) ? (Double) request.getAttribute("totalRevenue") : 0.0;

      out.write("\n");
      out.write("\n");
      out.write("  <!-- Navbar -->\n");
      out.write("  <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("      <a class=\"navbar-brand brand\" href=\"");
      out.print( request.getContextPath() );
      out.write("/owner/dashboard\">MotorHub Owner</a>\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#nav\" aria-controls=\"nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("      </button>\n");
      out.write("      <div id=\"nav\" class=\"collapse navbar-collapse\">\n");
      out.write("        <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("          <li class=\"nav-item\"><a class=\"nav-link active\" href=\"");
      out.print( request.getContextPath() );
      out.write("/owner/dashboard\">Dashboard</a></li>\n");
      out.write("          <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/owner/vehicles\">My Vehicles</a></li>\n");
      out.write("          <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/owner/bookings\">Bookings</a></li>\n");
      out.write("          <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/owner/revenue\">Revenue</a></li>\n");
      out.write("        </ul>\n");
      out.write("        <span class=\"navbar-text text-white me-3\">Hi, ");
      out.print( ownerName != null ? ownerName : "Owner" );
      out.write("</span>\n");
      out.write("        <a class=\"btn btn-outline-light\" href=\"");
      out.print( request.getContextPath() );
      out.write("/owner/logout\">Logout</a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </nav>\n");
      out.write("\n");
      out.write("  <!-- Content -->\n");
      out.write("  <div class=\"container py-5\">\n");
      out.write("    <div class=\"row g-4\">\n");
      out.write("      <div class=\"col-md-3\">\n");
      out.write("        <div class=\"card stat-card\">\n");
      out.write("          <div class=\"card-body\">\n");
      out.write("            <h6 class=\"text-muted\">Total Vehicles</h6>\n");
      out.write("            <div class=\"stat-value\">");
      out.print( totalVehicles );
      out.write("</div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-md-3\">\n");
      out.write("        <div class=\"card stat-card\">\n");
      out.write("          <div class=\"card-body\">\n");
      out.write("            <h6 class=\"text-muted\">Pending Bookings</h6>\n");
      out.write("            <div class=\"stat-value text-warning\">");
      out.print( pendingBookings );
      out.write("</div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-md-3\">\n");
      out.write("        <div class=\"card stat-card\">\n");
      out.write("          <div class=\"card-body\">\n");
      out.write("            <h6 class=\"text-muted\">Approved Bookings</h6>\n");
      out.write("            <div class=\"stat-value text-success\">");
      out.print( approvedBookings );
      out.write("</div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-md-3\">\n");
      out.write("        <div class=\"card stat-card\">\n");
      out.write("          <div class=\"card-body\">\n");
      out.write("            <h6 class=\"text-muted\">Total Revenue</h6>\n");
      out.write("            <div class=\"stat-value\">â¹ ");
      out.print( String.format("%.2f", totalRevenue) );
      out.write("</div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"mt-5\">\n");
      out.write("      <a href=\"");
      out.print( request.getContextPath() );
      out.write("/owner/vehicles\" class=\"btn btn-primary me-2\">Manage Vehicles</a>\n");
      out.write("      <a href=\"");
      out.print( request.getContextPath() );
      out.write("/owner/bookings\" class=\"btn btn-outline-secondary me-2\">Manage Bookings</a>\n");
      out.write("      <a href=\"");
      out.print( request.getContextPath() );
      out.write("/owner/revenue\" class=\"btn btn-outline-dark\">View Revenue</a>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
