/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2025-10-12 17:46:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.owner;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class vehicle_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"ISO-8859-1\">\n");
      out.write("  <title>Vehicle Form</title>\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");

  response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
  if (session.getAttribute("owner_id") == null) {
    response.sendRedirect(request.getContextPath() + "/owner/login");
    return;
  }
  String mode = (String) request.getAttribute("mode");
  boolean isEdit = "edit".equals(mode);

      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\n");
      out.write("  <div class=\"container-fluid\">\n");
      out.write("    <a class=\"navbar-brand\" href=\"");
      out.print( request.getContextPath() );
      out.write("/owner/dashboard\">MotorHub Owner</a>\n");
      out.write("    <div class=\"collapse navbar-collapse\">\n");
      out.write("      <ul class=\"navbar-nav me-auto\">\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/owner/vehicles\">My Vehicles</a></li>\n");
      out.write("      </ul>\n");
      out.write("      <a class=\"btn btn-outline-light\" href=\"");
      out.print( request.getContextPath() );
      out.write("/owner/logout\">Logout</a>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"container py-4\">\n");
      out.write("  <div class=\"row justify-content-center\">\n");
      out.write("    <div class=\"col-lg-8\">\n");
      out.write("      <div class=\"card shadow-sm\">\n");
      out.write("        <div class=\"card-body p-4\">\n");
      out.write("          <h3 class=\"mb-3\">");
      out.print( isEdit ? "Edit Vehicle" : "Add Vehicle" );
      out.write("</h3>\n");
      out.write("\n");
      out.write("          <form action=\"");
      out.print( request.getContextPath() );
      out.print( isEdit ? "/owner/vehicles/edit" : "/owner/vehicles/new" );
      out.write("\" method=\"POST\" ");
      out.print( isEdit ? "" : "enctype=\"multipart/form-data\"" );
      out.write(">\n");
      out.write("            ");
 if (isEdit) { 
      out.write("\n");
      out.write("              <input type=\"hidden\" name=\"vehicle_id\" value=\"");
      out.print( request.getAttribute("vehicle_id") );
      out.write("\">\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"row g-3\">\n");
      out.write("              <div class=\"col-md-6\">\n");
      out.write("                <label class=\"form-label\">Vehicle Name</label>\n");
      out.write("                <input type=\"text\" name=\"vehicle_name\" class=\"form-control\" value=\"");
      out.print( request.getAttribute("vehicle_name") != null ? request.getAttribute("vehicle_name") : "" );
      out.write("\" required>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-md-6\">\n");
      out.write("                <label class=\"form-label\">Vehicle Model</label>\n");
      out.write("                <input type=\"text\" name=\"vehicle_model\" class=\"form-control\" value=\"");
      out.print( request.getAttribute("vehicle_model") != null ? request.getAttribute("vehicle_model") : "" );
      out.write("\" placeholder=\"e.g., Swift, Activa, Classic 350\">\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-md-6\">\n");
      out.write("                <label class=\"form-label\">Vehicle Type</label>\n");
      out.write("                <select class=\"form-select\" name=\"vehicle_type\" required>\n");
      out.write("                  <option value=\"Car\" ");
      out.print( "Car".equals(request.getAttribute("vehicle_type")) ? "selected" : "" );
      out.write(">Car</option>\n");
      out.write("                  <option value=\"Bike\" ");
      out.print( "Bike".equals(request.getAttribute("vehicle_type")) ? "selected" : "" );
      out.write(">Bike</option>\n");
      out.write("                  <option value=\"Scooter\" ");
      out.print( "Scooter".equals(request.getAttribute("vehicle_type")) ? "selected" : "" );
      out.write(">Scooter</option>\n");
      out.write("                </select>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-md-6\">\n");
      out.write("                <label class=\"form-label\">Registration Number</label>\n");
      out.write("                <input type=\"text\" name=\"vehicle_number\" class=\"form-control\" value=\"");
      out.print( request.getAttribute("vehicle_number") != null ? request.getAttribute("vehicle_number") : "" );
      out.write("\" required>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-md-6\">\n");
      out.write("                <label class=\"form-label\">Rent Per Day</label>\n");
      out.write("                <input type=\"number\" step=\"0.01\" min=\"0\" name=\"rent_per_day\" class=\"form-control\" value=\"");
      out.print( request.getAttribute("rent_per_day") != null ? request.getAttribute("rent_per_day") : "" );
      out.write("\" required>\n");
      out.write("              </div>\n");
      out.write("              ");
 if (isEdit) { 
      out.write("\n");
      out.write("              <div class=\"col-md-6\">\n");
      out.write("                <label class=\"form-label\">Status</label>\n");
      out.write("                <select class=\"form-select\" name=\"status\">\n");
      out.write("                  ");
 String currentStatus = (String) request.getAttribute("status"); if (currentStatus == null) currentStatus = "Available"; 
      out.write("\n");
      out.write("                  <option value=\"Available\" ");
      out.print( "Available".equals(currentStatus) ? "selected" : "" );
      out.write(">Available</option>\n");
      out.write("                  <option value=\"On Trip\" ");
      out.print( "On Trip".equals(currentStatus) ? "selected" : "" );
      out.write(">On Trip</option>\n");
      out.write("                  <option value=\"Maintenance\" ");
      out.print( "Maintenance".equals(currentStatus) ? "selected" : "" );
      out.write(">Maintenance</option>\n");
      out.write("                </select>\n");
      out.write("              </div>\n");
      out.write("              ");
 } 
      out.write("\n");
      out.write("              ");
 if (!isEdit) { 
      out.write("\n");
      out.write("              <div class=\"col-md-12\">\n");
      out.write("                <label class=\"form-label\">Photo</label>\n");
      out.write("                <input type=\"file\" name=\"image\" accept=\"image/*\" class=\"form-control\">\n");
      out.write("              </div>\n");
      out.write("              ");
 } 
      out.write("\n");
      out.write("              ");
 if (isEdit) { 
      out.write("\n");
      out.write("              <div class=\"col-md-12 form-check mt-3\">\n");
      out.write("                <input class=\"form-check-input\" type=\"checkbox\" name=\"availability\" id=\"avail\" ");
      out.print( Boolean.TRUE.equals(request.getAttribute("availability")) ? "checked" : "" );
      out.write(" >\n");
      out.write("                <label class=\"form-check-label\" for=\"avail\">Available</label>\n");
      out.write("              </div>\n");
      out.write("              ");
 } 
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"mt-4 d-flex gap-2\">\n");
      out.write("              <button type=\"submit\" class=\"btn btn-success\">");
      out.print( isEdit ? "Save Changes" : "Create Vehicle" );
      out.write("</button>\n");
      out.write("              <a href=\"");
      out.print( request.getContextPath() );
      out.write("/owner/vehicles\" class=\"btn btn-outline-secondary\">Cancel</a>\n");
      out.write("            </div>\n");
      out.write("          </form>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
