/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2025-10-14 06:31:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_005flogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>Admin Login - Vehicle Management</title>\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <style>\r\n");
      out.write("    body {\r\n");
      out.write("      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("      min-height: 100vh;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("    .login-card {\r\n");
      out.write("      background: rgba(255, 255, 255, 0.95);\r\n");
      out.write("      backdrop-filter: blur(10px);\r\n");
      out.write("      border-radius: 20px;\r\n");
      out.write("      box-shadow: 0 20px 40px rgba(0,0,0,0.1);\r\n");
      out.write("      border: 1px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("    }\r\n");
      out.write("    .admin-header {\r\n");
      out.write("      background: linear-gradient(45deg, #ff6b6b, #ee5a24);\r\n");
      out.write("      color: white;\r\n");
      out.write("      border-radius: 20px 20px 0 0;\r\n");
      out.write("      padding: 2rem;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .btn-admin {\r\n");
      out.write("      background: linear-gradient(45deg, #ff6b6b, #ee5a24);\r\n");
      out.write("      border: none;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      padding: 12px;\r\n");
      out.write("      color: white;\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("      transition: all 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("    .btn-admin:hover {\r\n");
      out.write("      background: linear-gradient(45deg, #ee5a24, #ff6b6b);\r\n");
      out.write("      color: white;\r\n");
      out.write("      transform: translateY(-2px);\r\n");
      out.write("      box-shadow: 0 8px 20px rgba(238, 90, 36, 0.3);\r\n");
      out.write("    }\r\n");
      out.write("    .form-control {\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      border: 2px solid #e9ecef;\r\n");
      out.write("      padding: 12px 15px;\r\n");
      out.write("      transition: all 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("    .form-control:focus {\r\n");
      out.write("      border-color: #ff6b6b;\r\n");
      out.write("      box-shadow: 0 0 0 0.2rem rgba(255, 107, 107, 0.25);\r\n");
      out.write("    }\r\n");
      out.write("    .alert-custom {\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      border: none;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row justify-content-center\">\r\n");
      out.write("      <div class=\"col-md-6 col-lg-5\">\r\n");
      out.write("        <div class=\"card login-card border-0\">\r\n");
      out.write("          <div class=\"admin-header\">\r\n");
      out.write("            <i class=\"fas fa-user-shield fa-3x mb-3\"></i>\r\n");
      out.write("            <h3 class=\"mb-0\">Admin Portal</h3>\r\n");
      out.write("            <p class=\"mb-0 mt-2 opacity-75\">Vehicle Management System</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"card-body p-4\">\r\n");
      out.write("            ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("              <div class=\"alert alert-danger alert-custom\">\r\n");
      out.write("                <i class=\"fas fa-exclamation-circle me-2\"></i>\r\n");
      out.write("                ");
      out.print( request.getAttribute("error") );
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <form action=\"");
      out.print( request.getContextPath() );
      out.write("/admin/login\" method=\"POST\">\r\n");
      out.write("              <div class=\"mb-4\">\r\n");
      out.write("                <label class=\"form-label fw-bold\">\r\n");
      out.write("                  <i class=\"fas fa-user me-2 text-muted\"></i>Username\r\n");
      out.write("                </label>\r\n");
      out.write("                <input type=\"text\" name=\"username\" class=\"form-control\" placeholder=\"Enter admin username\" required>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"mb-4\">\r\n");
      out.write("                <label class=\"form-label fw-bold\">\r\n");
      out.write("                  <i class=\"fas fa-lock me-2 text-muted\"></i>Password\r\n");
      out.write("                </label>\r\n");
      out.write("                <input type=\"password\" name=\"password\" class=\"form-control\" placeholder=\"Enter admin password\" required>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              <button type=\"submit\" class=\"btn btn-admin w-100 mb-3\">\r\n");
      out.write("                <i class=\"fas fa-sign-in-alt me-2\"></i>Admin Login\r\n");
      out.write("              </button>\r\n");
      out.write("            </form>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"text-center mt-4 pt-3 border-top\">\r\n");
      out.write("              <small class=\"text-muted\">\r\n");
      out.write("                <i class=\"fas fa-info-circle me-1\"></i>\r\n");
      out.write("                Default credentials: admin / admin123\r\n");
      out.write("              </small>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"text-center mt-3\">\r\n");
      out.write("              <a href=\"");
      out.print( request.getContextPath() );
      out.write("/\" class=\"text-decoration-none\">\r\n");
      out.write("                <i class=\"fas fa-arrow-left me-1\"></i>Back to Main Site\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
