/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2025-10-14 06:40:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>Admin Dashboard - Vehicle Management</title>\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <style>\r\n");
      out.write("    body { background: #f8f9fa; }\r\n");
      out.write("    .sidebar {\r\n");
      out.write("      background: linear-gradient(45deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("      min-height: 100vh;\r\n");
      out.write("      color: white;\r\n");
      out.write("    }\r\n");
      out.write("    .stat-card {\r\n");
      out.write("      border: 0;\r\n");
      out.write("      border-radius: 15px;\r\n");
      out.write("      box-shadow: 0 5px 15px rgba(0,0,0,0.08);\r\n");
      out.write("      transition: all 0.3s ease;\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("    .stat-card:hover {\r\n");
      out.write("      transform: translateY(-5px);\r\n");
      out.write("      box-shadow: 0 10px 25px rgba(0,0,0,0.15);\r\n");
      out.write("    }\r\n");
      out.write("    .stat-value {\r\n");
      out.write("      font-size: 2.5rem;\r\n");
      out.write("      font-weight: 700;\r\n");
      out.write("    }\r\n");
      out.write("    .nav-link {\r\n");
      out.write("      color: rgba(255,255,255,0.8);\r\n");
      out.write("      padding: 12px 20px;\r\n");
      out.write("      margin: 2px 0;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      transition: all 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("    .nav-link:hover, .nav-link.active {\r\n");
      out.write("      background: rgba(255,255,255,0.2);\r\n");
      out.write("      color: white;\r\n");
      out.write("    }\r\n");
      out.write("    .chart-card {\r\n");
      out.write("      border-radius: 15px;\r\n");
      out.write("      border: 0;\r\n");
      out.write("      box-shadow: 0 5px 15px rgba(0,0,0,0.08);\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

  response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
  if (session.getAttribute("admin_id") == null) {
    response.sendRedirect(request.getContextPath() + "/admin/login");
    return;
  }
  String adminName = (String) session.getAttribute("admin_name");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("    <!-- Sidebar -->\r\n");
      out.write("    <div class=\"col-md-3 col-lg-2 sidebar p-0\">\r\n");
      out.write("      <div class=\"p-4\">\r\n");
      out.write("        <div class=\"text-center mb-4\">\r\n");
      out.write("          <i class=\"fas fa-user-shield fa-3x mb-3\"></i>\r\n");
      out.write("          <h4>Admin Panel</h4>\r\n");
      out.write("          <p class=\"small opacity-75\">Welcome, ");
      out.print( adminName );
      out.write("</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <nav class=\"nav flex-column\">\r\n");
      out.write("          <a class=\"nav-link active\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/dashboard\">\r\n");
      out.write("            <i class=\"fas fa-tachometer-alt me-2\"></i>Dashboard\r\n");
      out.write("          </a>\r\n");
      out.write("          <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/vehicles\">\r\n");
      out.write("            <i class=\"fas fa-car me-2\"></i>Vehicles\r\n");
      out.write("          </a>\r\n");
      out.write("          <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/owners\">\r\n");
      out.write("            <i class=\"fas fa-users me-2\"></i>Owners\r\n");
      out.write("          </a>\r\n");
      out.write("          <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/users\">\r\n");
      out.write("            <i class=\"fas fa-user me-2\"></i>Users\r\n");
      out.write("          </a>\r\n");
      out.write("          <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/trips\">\r\n");
      out.write("            <i class=\"fas fa-route me-2\"></i>Trips\r\n");
      out.write("          </a>\r\n");
      out.write("          <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/maintenance\">\r\n");
      out.write("            <i class=\"fas fa-tools me-2\"></i>Maintenance\r\n");
      out.write("          </a>\r\n");
      out.write("          <hr class=\"my-3 opacity-50\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/logout\">\r\n");
      out.write("            <i class=\"fas fa-sign-out-alt me-2\"></i>Logout\r\n");
      out.write("          </a>\r\n");
      out.write("        </nav>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Main Content -->\r\n");
      out.write("    <div class=\"col-md-9 col-lg-10\">\r\n");
      out.write("      <div class=\"p-4\">\r\n");
      out.write("        <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("          <h1 class=\"h3 mb-0\">Dashboard Overview</h1>\r\n");
      out.write("          <div class=\"text-muted\">\r\n");
      out.write("            <i class=\"fas fa-calendar me-1\"></i>\r\n");
      out.write("            ");
      out.print( new java.text.SimpleDateFormat("EEEE, MMMM dd, yyyy").format(new java.util.Date()) );
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Key Metrics Row -->\r\n");
      out.write("        <div class=\"row g-4 mb-4\">\r\n");
      out.write("          <div class=\"col-md-3\">\r\n");
      out.write("            <div class=\"card stat-card bg-primary text-white\">\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                  <div>\r\n");
      out.write("                    <p class=\"mb-1 opacity-75\">Total Users</p>\r\n");
      out.write("                    <div class=\"stat-value\">");
      out.print( request.getAttribute("totalUsers") );
      out.write("</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <i class=\"fas fa-users fa-2x opacity-50\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"col-md-3\">\r\n");
      out.write("            <div class=\"card stat-card bg-success text-white\">\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                  <div>\r\n");
      out.write("                    <p class=\"mb-1 opacity-75\">Total Owners</p>\r\n");
      out.write("                    <div class=\"stat-value\">");
      out.print( request.getAttribute("totalOwners") );
      out.write("</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <i class=\"fas fa-user-tie fa-2x opacity-50\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"col-md-3\">\r\n");
      out.write("            <div class=\"card stat-card bg-info text-white\">\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                  <div>\r\n");
      out.write("                    <p class=\"mb-1 opacity-75\">Total Vehicles</p>\r\n");
      out.write("                    <div class=\"stat-value\">");
      out.print( request.getAttribute("totalVehicles") );
      out.write("</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <i class=\"fas fa-car fa-2x opacity-50\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"col-md-3\">\r\n");
      out.write("            <div class=\"card stat-card bg-warning text-white\">\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                  <div>\r\n");
      out.write("                    <p class=\"mb-1 opacity-75\">Total Bookings</p>\r\n");
      out.write("                    <div class=\"stat-value\">");
      out.print( request.getAttribute("totalBookings") );
      out.write("</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <i class=\"fas fa-calendar-check fa-2x opacity-50\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Financial Overview -->\r\n");
      out.write("        <div class=\"row g-4 mb-4\">\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"card stat-card\">\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h6 class=\"text-muted\">Total Revenue</h6>\r\n");
      out.write("                <div class=\"h3 text-success\">₹ ");
      out.print( String.format("%.2f", (Double) request.getAttribute("totalRevenue")) );
      out.write("</div>\r\n");
      out.write("                <small class=\"text-muted\">\r\n");
      out.write("                  <i class=\"fas fa-arrow-up text-success me-1\"></i>From completed bookings\r\n");
      out.write("                </small>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"card stat-card\">\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h6 class=\"text-muted\">Pending Amount</h6>\r\n");
      out.write("                <div class=\"h3 text-warning\">₹ ");
      out.print( String.format("%.2f", (Double) request.getAttribute("pendingAmount")) );
      out.write("</div>\r\n");
      out.write("                <small class=\"text-muted\">\r\n");
      out.write("                  <i class=\"fas fa-clock text-warning me-1\"></i>Pending & approved bookings\r\n");
      out.write("                </small>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"card stat-card\">\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h6 class=\"text-muted\">Maintenance Cost</h6>\r\n");
      out.write("                <div class=\"h3 text-danger\">₹ ");
      out.print( String.format("%.2f", (Double) request.getAttribute("maintenanceCost")) );
      out.write("</div>\r\n");
      out.write("                <small class=\"text-muted\">\r\n");
      out.write("                  <i class=\"fas fa-tools text-danger me-1\"></i>Last 30 days\r\n");
      out.write("                </small>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Status Breakdown -->\r\n");
      out.write("        <div class=\"row g-4\">\r\n");
      out.write("          <!-- User Status -->\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"card chart-card\">\r\n");
      out.write("              <div class=\"card-header bg-transparent\">\r\n");
      out.write("                <h6 class=\"mb-0\"><i class=\"fas fa-users me-2\"></i>User Status</h6>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <div class=\"d-flex justify-content-between align-items-center mb-2\">\r\n");
      out.write("                  <span>Active</span>\r\n");
      out.write("                  <span class=\"badge bg-success\">");
      out.print( request.getAttribute("activeUsers") );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"d-flex justify-content-between align-items-center mb-2\">\r\n");
      out.write("                  <span>Pending</span>\r\n");
      out.write("                  <span class=\"badge bg-warning\">");
      out.print( request.getAttribute("pendingUsers") );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                  <span>Suspended</span>\r\n");
      out.write("                  <span class=\"badge bg-danger\">");
      out.print( request.getAttribute("suspendedUsers") );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- Vehicle Status -->\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"card chart-card\">\r\n");
      out.write("              <div class=\"card-header bg-transparent\">\r\n");
      out.write("                <h6 class=\"mb-0\"><i class=\"fas fa-car me-2\"></i>Vehicle Status</h6>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <div class=\"d-flex justify-content-between align-items-center mb-2\">\r\n");
      out.write("                  <span>Available</span>\r\n");
      out.write("                  <span class=\"badge bg-success\">");
      out.print( request.getAttribute("availableVehicles") );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"d-flex justify-content-between align-items-center mb-2\">\r\n");
      out.write("                  <span>On Trip</span>\r\n");
      out.write("                  <span class=\"badge bg-warning\">");
      out.print( request.getAttribute("onTripVehicles") );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                  <span>Maintenance</span>\r\n");
      out.write("                  <span class=\"badge bg-danger\">");
      out.print( request.getAttribute("maintenanceVehicles") );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- Booking Status -->\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"card chart-card\">\r\n");
      out.write("              <div class=\"card-header bg-transparent\">\r\n");
      out.write("                <h6 class=\"mb-0\"><i class=\"fas fa-calendar-check me-2\"></i>Booking Status</h6>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <div class=\"d-flex justify-content-between align-items-center mb-2\">\r\n");
      out.write("                  <span>Pending</span>\r\n");
      out.write("                  <span class=\"badge bg-warning\">");
      out.print( request.getAttribute("pendingBookings") );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"d-flex justify-content-between align-items-center mb-2\">\r\n");
      out.write("                  <span>Approved</span>\r\n");
      out.write("                  <span class=\"badge bg-info\">");
      out.print( request.getAttribute("approvedBookings") );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                  <span>Completed</span>\r\n");
      out.write("                  <span class=\"badge bg-success\">");
      out.print( request.getAttribute("completedBookings") );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Recent Activity -->\r\n");
      out.write("        <div class=\"row g-4 mt-2\">\r\n");
      out.write("          <div class=\"col-12\">\r\n");
      out.write("            <div class=\"card chart-card\">\r\n");
      out.write("              <div class=\"card-header bg-transparent\">\r\n");
      out.write("                <h6 class=\"mb-0\"><i class=\"fas fa-chart-line me-2\"></i>Recent Activity (Last 7 Days)</h6>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <div class=\"row text-center\">\r\n");
      out.write("                  <div class=\"col-md-6\">\r\n");
      out.write("                    <div class=\"border-end\">\r\n");
      out.write("                      <div class=\"h2 text-primary\">");
      out.print( request.getAttribute("recentBookings") );
      out.write("</div>\r\n");
      out.write("                      <p class=\"text-muted mb-0\">New Bookings</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-6\">\r\n");
      out.write("                    <div class=\"h2 text-success\">");
      out.print( request.getAttribute("recentRegistrations") );
      out.write("</div>\r\n");
      out.write("                    <p class=\"text-muted mb-0\">New Registrations</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
