/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2025-10-12 16:36:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.vehicle.Vehicle;
import com.vehicle.Area;
import com.vehicle.City;
import com.vehicle.State;
import com.vehicle.Zip;

public final class car_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("com.vehicle.Zip");
    _jspx_imports_classes.add("com.vehicle.Vehicle");
    _jspx_imports_classes.add("com.vehicle.State");
    _jspx_imports_classes.add("com.vehicle.City");
    _jspx_imports_classes.add("com.vehicle.Area");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Cars</title>\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@500&family=Ubuntu:wght@700&display=swap\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");

		response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
	    	if(session.getAttribute("user_id") == null)
	    		response.sendRedirect("/Vehicle/login");
	  
	    	session = request.getSession();
	    	String name = (String)session.getAttribute("name");
	
      out.write("\n");
      out.write("\n");
      out.write("	<style>\n");
      out.write("    	body {\n");
      out.write("            /* background-color: #EEEEEE; */\n");
      out.write("            font-family: 'Poppins', sans-serif;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .navbar {\n");
      out.write("            background-color: #00ADB5 !important;\n");
      out.write("        }\n");
      out.write("            \n");
      out.write("		.logout {\n");
      out.write("			color: white;\n");
      out.write("			margin-right: 5rem;\n");
      out.write("		}\n");
      out.write("        \n");
      out.write("        .navbar-brand {\n");
      out.write("        	margin-left: 5rem !important;\n");
      out.write("        	font-family: 'Poppins', sans-serif !important;\n");
      out.write("        	font-size: 2.5rem !important;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .act-cust {\n");
      out.write("        	color: #D6E4F0!important;\n");
      out.write("        	border-bottom: 4px solid white !important;\n");
      out.write("        }\n");
      out.write("       \n");
      out.write("       .nav-item {\n");
      out.write("       		font-family: 'Poppins', sans-serif !important;\n");
      out.write("       		font-size: 1.2rem;\n");
      out.write("       		margin-left: 1rem;\n");
      out.write("       }\n");
      out.write("       \n");
      out.write("       .nav-link {\n");
      out.write("       		/*color: white !important;*/\n");
      out.write("       }\n");
      out.write("       \n");
      out.write("       /* Styles for filers */\n");
      out.write("	   .form-range {\n");
      out.write("		   width: 80%;\n");
      out.write("	   } \n");
      out.write("       \n");
      out.write("	   .filters-div {\n");
      out.write("		   margin-left: 20px;\n");
      out.write("	   }\n");
      out.write("	   \n");
      out.write("	   .nav-name {\n");
      out.write("			color: #F8F3D4 !important;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.vehicle-card {\n");
      out.write("			width: 65.5rem;\n");
      out.write("			margin-top: 2rem;\n");
      out.write("			border-radius: 10px;\n");
      out.write("			box-shadow: 5px 5px 5px rgb(60, 81, 85);\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.veh-img {\n");
      out.write("			width: 500px;\n");
      out.write("			height: 300px;\n");
      out.write("			border-radius: 30px;\n");
      out.write("			margin-left: 10rem;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.card-head {\n");
      out.write("			margin-top: 20px;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.book-btn {\n");
      out.write("			margin-left: 25rem;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.table {\n");
      out.write("			margin-top: 20px;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("			/* Footer Section */\n");
      out.write("\n");
      out.write("		#ganesh {\n");
      out.write("		    font-family: 'Ubuntu', sans-serif;\n");
      out.write("		    font-size: 20px;\n");
      out.write("		    padding-bottom: 20px;\n");
      out.write("		    margin-left: 3rem;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.fth {\n");
      out.write("		    margin-top: 70px;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.footer {\n");
      out.write("		    position: absolute;\n");
      out.write("		    margin-top: 2rem;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.footer-item {\n");
      out.write("		    padding-top: 10px;\n");
      out.write("		    margin-left: 550px;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.social-icon {\n");
      out.write("		    color: #000;\n");
      out.write("		    margin-left: 50px;\n");
      out.write("		    font-size: 30px;\n");
      out.write("		    padding-bottom: 20px;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		#copyright {\n");
      out.write("		    font-family: 'Ubuntu', sans-serif;\n");
      out.write("		    font-size: 16px;\n");
      out.write("		    margin-left: 80px;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.nav-name {\n");
      out.write("			color: #F8F3D4 !important;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		\n");
      out.write("    </style>\n");
      out.write("	\n");
      out.write("    <!-- Navbar -->\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <a class=\"navbar-brand\" href=\"#\">MotorHub</a>\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("            </button>\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("                <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link active\" href=\"/Vehicle/dashboard\">Dashboard</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                    	<a class=\"nav-link active act-cust\" href=\"/Vehicle/car\">Buy a Car</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                    	<a class=\"nav-link active\" href=\"/Vehicle/bike\">Buy a Bike</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                    	<a class=\"nav-link active\" href=\"/Vehicle/sell\">Sell your vehicle</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                    	<a class=\"nav-link active\" href=\"/Vehicle/orders\">My Orders</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                    	<a class=\"nav-link active nav-name\">");
      out.print( name );
      out.write("</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("                <a href=\"/Vehicle/logout\"><Button class=\"btn btn-danger logout\">Logout</Button></a><br /><br />\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("     </nav>\n");
      out.write("     \n");
      out.write("    \n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("	  <div class=\"row\">\n");
      out.write("	    <div class=\"col-md-3\">\n");
      out.write("	      <div class=\"filters-div\">\n");
      out.write("	      \n");
      out.write("	      <h3 style=\"margin-top: 2rem;\">Filters</h3>\n");
      out.write("	      <p>Filter By Price</p>\n");
      out.write("		    <form action=\"/Vehicle/filterpricecar\" method=\"POST\">\n");
      out.write("			    <label for=\"customRange2\" class=\"form-label\">Select Price Range</label>\n");
      out.write("				<input name=\"price_range\" type=\"range\" class=\"form-range\" min=\"100000\" max=\"10000000\" step=\"5000\" value=\"5000000\" id=\"customRange2\" onChange=\"this.form.submit()\">\n");
      out.write("				<p>Rs 10L<span style=\"margin-left: 9rem;\">Rs 1 Crore</</span></p>\n");
      out.write("		    </form>\n");
      out.write("		    \n");
      out.write("		    <form action=\"/Vehicle/filterareacar\" method=\"POST\">\n");
      out.write("		    	<p style=\"margin-top: 30px;\">Filter By Area</p>\n");
      out.write("		    	");
 ArrayList<Area> areaList = (ArrayList)request.getAttribute("areaList"); 
      out.write("\n");
      out.write("		    	");
 if(!areaList.isEmpty()){ 
      out.write("\n");
      out.write("		    		");
 for(int i=0; i<areaList.size(); i++){ 
      out.write("\n");
      out.write("		    			");
 Area area = (Area)areaList.get(i); 
      out.write("\n");
      out.write("		    			<div class=\"form-check\">\n");
      out.write("							<input name=\"area\" class=\"form-check-input\" type=\"checkbox\" value=\"");
      out.print( area.getArea() );
      out.write("\" id=\"flexCheckDefault\" onChange=\"this.form.submit()\">\n");
      out.write("							<label class=\"form-check-label\" for=\"flexCheckDefault\">\n");
      out.write("							    ");
 out.println(area.getArea()); 
      out.write("\n");
      out.write("							</label>\n");
      out.write("						</div>\n");
      out.write("		    		");
 } 
      out.write("\n");
      out.write("		    	");
 } 
      out.write("\n");
      out.write("		    </form>\n");
      out.write("		    \n");
      out.write("		    <form action=\"/Vehicle/filtercitycar\" method=\"POST\">\n");
      out.write("		    	<p style=\"margin-top: 30px;\">Filter By City</p>\n");
      out.write("		    	");
 ArrayList<City> cityList = (ArrayList)request.getAttribute("cityList"); 
      out.write("\n");
      out.write("		    	");
 if(!cityList.isEmpty()){ 
      out.write("\n");
      out.write("		    		");
 for(int i=0; i<cityList.size(); i++){ 
      out.write("\n");
      out.write("		    			");
 City city = (City)cityList.get(i); 
      out.write("\n");
      out.write("		    			<div class=\"form-check\">\n");
      out.write("							<input name=\"city\" class=\"form-check-input\" type=\"checkbox\" value=\"");
      out.print( city.getCity() );
      out.write("\" id=\"flexCheckDefault\" onChange=\"this.form.submit()\">\n");
      out.write("							<label class=\"form-check-label\" for=\"flexCheckDefault\">\n");
      out.write("							    ");
 out.println(city.getCity()); 
      out.write("\n");
      out.write("							</label>\n");
      out.write("						</div>\n");
      out.write("		    		");
 } 
      out.write("\n");
      out.write("		    	");
 } 
      out.write("\n");
      out.write("		    </form>\n");
      out.write("		    \n");
      out.write("		    <form action=\"/Vehicle/filterstatecar\" method=\"POST\">\n");
      out.write("		    	<p style=\"margin-top: 30px;\">Filter By State</p>\n");
      out.write("		    	");
 ArrayList<State> stateList = (ArrayList)request.getAttribute("stateList"); 
      out.write("\n");
      out.write("		    	");
 if(!stateList.isEmpty()){ 
      out.write("\n");
      out.write("		    		");
 for(int i=0; i<stateList.size(); i++){ 
      out.write("\n");
      out.write("		    			");
 State state = (State)stateList.get(i); 
      out.write("\n");
      out.write("		    			<div class=\"form-check\">\n");
      out.write("							<input name=\"state\" class=\"form-check-input\" type=\"checkbox\" value=\"");
      out.print( state.getState() );
      out.write("\" id=\"flexCheckDefault\" onChange=\"this.form.submit()\">\n");
      out.write("							<label class=\"form-check-label\" for=\"flexCheckDefault\">\n");
      out.write("							    ");
 out.println(state.getState()); 
      out.write("\n");
      out.write("							</label>\n");
      out.write("						</div>\n");
      out.write("		    		");
 } 
      out.write("\n");
      out.write("		    	");
 } 
      out.write("\n");
      out.write("		    </form>\n");
      out.write("		    \n");
      out.write("		    <form action=\"/Vehicle/filterzipcar\" method=\"POST\">\n");
      out.write("		    	<p style=\"margin-top: 30px;\">Filter By Zip</p>\n");
      out.write("		    	");
 ArrayList<Zip> zipList = (ArrayList)request.getAttribute("zipList"); 
      out.write("\n");
      out.write("		    	");
 if(!zipList.isEmpty()){ 
      out.write("\n");
      out.write("		    		");
 for(int i=0; i<zipList.size(); i++){ 
      out.write("\n");
      out.write("		    			");
 Zip zip = (Zip)zipList.get(i); 
      out.write("\n");
      out.write("		    			<div class=\"form-check\">\n");
      out.write("							<input name=\"zip\" class=\"form-check-input\" type=\"checkbox\" value=\"");
      out.print( zip.getZip() );
      out.write("\" id=\"flexCheckDefault\" onChange=\"this.form.submit()\">\n");
      out.write("							<label class=\"form-check-label\" for=\"flexCheckDefault\">\n");
      out.write("							    ");
 out.println(zip.getZip()); 
      out.write("\n");
      out.write("							</label>\n");
      out.write("						</div>\n");
      out.write("		    		");
 } 
      out.write("\n");
      out.write("		    	");
 } 
      out.write("\n");
      out.write("		    </form>\n");
      out.write("	      </div>\n");
      out.write("	    </div>\n");
      out.write("	    \n");
      out.write("	    \n");
      out.write("	    <div class=\"col-md-9\">\n");
      out.write("			");
 ArrayList<Vehicle> carList = (ArrayList)request.getAttribute("carList"); 
      out.write("\n");
      out.write("			<h2 class=\"card-head\">Available cars ");
      out.print(carList.size());
      out.write("</h2>\n");
      out.write("    \n");
      out.write("   			");
 if(!carList.isEmpty()) { 
      out.write("\n");
      out.write("				");
 for(int i=0; i<carList.size(); i++){ 
      out.write("\n");
      out.write("					");
 Vehicle car = (Vehicle)carList.get(i); 
      out.write("\n");
      out.write("					<div class=\"card vehicle-card\">\n");
      out.write("						<div class=\"card-body\">\n");
      out.write("							<div class=\"row\">\n");
      out.write("								<div class=\"col-md-12\">\n");
      out.write("									<img class=\"veh-img\" src=\"");
 out.println(car.getImage()); 
      out.write("\">\n");
      out.write("								</div>\n");
      out.write("								\n");
      out.write("							</div>\n");
      out.write("							\n");
      out.write("							<table class=\"table table-hover table-borderless\">\n");
      out.write("								<div class=\"row\">\n");
      out.write("									<div class=\"col-md-12\">\n");
      out.write("										<thead>\n");
      out.write("											<tr>\n");
      out.write("												<th scope=\"col\">Vehicle_id</th>\n");
      out.write("												<th scope=\"col\">Type</th>\n");
      out.write("												<th scope=\"col\">Model</th>\n");
      out.write("												<th scope=\"col\">Color</th>\n");
      out.write("											</tr>\n");
      out.write("										</thead>\n");
      out.write("										<tbody>\n");
      out.write("											<tr>\n");
      out.write("												<td>");
 out.println(car.getV_id()); 
      out.write("</td>\n");
      out.write("												<td>");
 out.println(car.getType()); 
      out.write("</td>\n");
      out.write("												<td>");
 out.println(car.getModel()); 
      out.write("</td>\n");
      out.write("												<td>");
 out.println(car.getColor()); 
      out.write("</td>\n");
      out.write("											</tr>\n");
      out.write("										</tbody>		\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("\n");
      out.write("								<div class=\"row\">\n");
      out.write("									<div class=\"col-md-12\">\n");
      out.write("										<thead>\n");
      out.write("											<tr>\n");
      out.write("												<th scope=\"col\">Reg. Date</th>\n");
      out.write("												<th scope=\"col\">Price</th>\n");
      out.write("												<th scope=\"col\">Area</th>\n");
      out.write("												<th scope=\"col\">City</th>\n");
      out.write("											</tr>\n");
      out.write("										</thead>\n");
      out.write("										<tbody>\n");
      out.write("											<tr>\n");
      out.write("												<td>");
 out.println(car.getReg_date()); 
      out.write("</td>\n");
      out.write("												<td>");
 out.println(car.getPrice()); 
      out.write("</td>\n");
      out.write("												<td>");
 out.println(car.getArea()); 
      out.write("</td>\n");
      out.write("												<td>");
 out.println(car.getCity()); 
      out.write("</td>\n");
      out.write("											</tr>\n");
      out.write("										</tbody>		\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("								<div class=\"row\">\n");
      out.write("									<div class=\"col-md-12\">\n");
      out.write("										<thead>\n");
      out.write("											<tr>\n");
      out.write("												<th scope=\"col\">State</th>\n");
      out.write("												<th scope=\"col\">Zip</th>\n");
      out.write("												<th scope=\"col\">Owner_id</th>\n");
      out.write("												<th scope=\"col\">Fuel_type</th>\n");
      out.write("											</tr>\n");
      out.write("										</thead>\n");
      out.write("										<tbody>\n");
      out.write("											<tr>\n");
      out.write("												<td>");
 out.println(car.getState()); 
      out.write("</td>\n");
      out.write("												<td>");
 out.println(car.getZip()); 
      out.write("</td>\n");
      out.write("												<td>");
 out.println(car.getOwner_id()); 
      out.write("</td>\n");
      out.write("												<td>");
 out.println(car.getFuel_type()); 
      out.write("</td>\n");
      out.write("											</tr>\n");
      out.write("										</tbody>		\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("\n");
      out.write("								<div class=\"row\">\n");
      out.write("									<div class=\"col-md-12\">\n");
      out.write("										<thead>\n");
      out.write("											<tr>\n");
      out.write("												<th scope=\"col\">Gear</th>\n");
      out.write("											</tr>\n");
      out.write("										</thead>\n");
      out.write("										<tbody>\n");
      out.write("											<tr>\n");
      out.write("												<td>");
 out.println(car.getGear()); 
      out.write("</td>\n");
      out.write("											</tr>\n");
      out.write("								</div>\n");
      out.write("							</table>\n");
      out.write("							<div class=\"row\">\n");
      out.write("								<div class=\"col-md-12\">\n");
      out.write("									<form action=\"/Vehicle/book\" method=\"POST\" class=\"row g-2 align-items-end\">\n");
      out.write("										<div class=\"col-auto\">\n");
      out.write("											<label class=\"form-label\">Start</label>\n");
      out.write("											<input type=\"date\" name=\"start_date\" class=\"form-control\" required>\n");
      out.write("										</div>\n");
      out.write("										<div class=\"col-auto\">\n");
      out.write("											<label class=\"form-label\">End</label>\n");
      out.write("											<input type=\"date\" name=\"end_date\" class=\"form-control\" required>\n");
      out.write("										</div>\n");
      out.write("										<div class=\"col-auto\">\n");
      out.write("											<button type=\"submit\" class=\"btn btn-dark book-btn\" name=\"v_id\" value=\"");
      out.print( car.getV_id() );
      out.write("\">Book Vehicle</button>\n");
      out.write("										</div>\n");
      out.write("									</form>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				");
 } 
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write(" \n");
      out.write(" 	<!-- Footer -->\n");
      out.write("    <footer class=\"footer\">\n");
      out.write("        <div class=\"footer-item\">\n");
      out.write("        <h1 id=\"ganesh\">Developed by Ganesh Sindagi</h1>\n");
      out.write("        <a href=\"https://www.facebook.com/ganesh.sindagi.3\"><i class=\"social-icon fab fa-facebook-f\"></i></a>\n");
      out.write("        <a href=\"https://twitter.com/GaneshSindagi\"><i class=\"social-icon fab fa-twitter\"></i></a>\n");
      out.write("        <a href=\"https://www.instagram.com/ganesh_sindagi/\"><i class=\"social-icon fab fa-instagram\"></i></a>\n");
      out.write("        <a href = \"mailto:ganeshsindagi7@gmail.com\"><i class=\"social-icon fas fa-envelope\"></i></a>\n");
      out.write("        <p id=\"copyright\">Copyright 2020 MotorHub</p>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("    <!-- jQuery and JS bundle w/ Popper.js -->\n");
      out.write("    <script src=\"https://kit.fontawesome.com/b6a0edf9cb.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    \n");
      out.write("    <!-- JavaScript Bundle with Popper -->\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\" crossorigin=\"anonymous\"></script>\n");
      out.write(" \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
