/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2025-10-12 16:36:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Vehicle Management System</title>\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@500&family=Ubuntu:wght@700&display=swap\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
 
    	response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
    	if(session.getAttribute("user_id") == null)
    		response.sendRedirect("/Vehicle/login");
  
    	session = request.getSession();
    	String name = (String)session.getAttribute("name");
    
      out.write("\n");
      out.write("    \n");
      out.write("    <style>\n");
      out.write("    	body {\n");
      out.write("            background-color: #EEEEEE;\n");
      out.write("            font-family: 'Poppins', sans-serif;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .navbar {\n");
      out.write("            background-color: #00ADB5 !important;\n");
      out.write("        }\n");
      out.write("            \n");
      out.write("		.logout {\n");
      out.write("			color: white;\n");
      out.write("			margin-right: 5rem;\n");
      out.write("			font-size: 1.1rem;\n");
      out.write("		}\n");
      out.write("        \n");
      out.write("        .navbar-brand {\n");
      out.write("        	margin-left: 5rem !important;\n");
      out.write("        	font-family: 'Poppins', sans-serif !important;\n");
      out.write("        	font-size: 2.5rem !important;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .act-cust {\n");
      out.write("        	color: #D6E4F0!important;\n");
      out.write("        	border-bottom: 4px solid white !important;\n");
      out.write("        }\n");
      out.write("       \n");
      out.write("       .nav-item {\n");
      out.write("       		font-family: 'Poppins', sans-serif !important;\n");
      out.write("       		font-size: 1.2rem;\n");
      out.write("       		margin-left: 1rem;\n");
      out.write("       }\n");
      out.write("       \n");
      out.write("       .nav-link {\n");
      out.write("       		/*color: white !important;*/\n");
      out.write("       }\n");
      out.write("       \n");
      out.write("       .namehead {\n");
      out.write("       		font-family: 'Poppins', sans-serif !important;\n");
      out.write("       		font-size: 3rem;\n");
      out.write("       		margin-top: 2rem;\n");
      out.write("       		margin-left: 9rem;\n");
      out.write("       		color: #222831;\n");
      out.write("       }\n");
      out.write("       \n");
      out.write("       .card {\n");
      out.write("		    margin: 3rem 2rem;\n");
      out.write("		    object-fit: scale-down;\n");
      out.write("		    border-radius: 7%;\n");
      out.write("		    overflow: hidden;\n");
      out.write("		    box-shadow: 5px 5px 5px rgb(60, 81, 85);\n");
      out.write("		    transition-delay: 100ms;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		/* Footer Section */\n");
      out.write("\n");
      out.write("		#ganesh {\n");
      out.write("		    font-family: 'Ubuntu', sans-serif;\n");
      out.write("		    font-size: 20px;\n");
      out.write("		    padding-bottom: 20px;\n");
      out.write("		    margin-left: 3rem;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.fth {\n");
      out.write("		    margin-top: 70px;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.footer {\n");
      out.write("		    position: absolute;\n");
      out.write("		    margin-top: 2rem;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.footer-item {\n");
      out.write("		    padding-top: 10px;\n");
      out.write("		    margin-left: 550px;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.social-icon {\n");
      out.write("		    color: #000;\n");
      out.write("		    margin-left: 50px;\n");
      out.write("		    font-size: 30px;\n");
      out.write("		    padding-bottom: 20px;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		#copyright {\n");
      out.write("		    font-family: 'Ubuntu', sans-serif;\n");
      out.write("		    font-size: 16px;\n");
      out.write("		    margin-left: 80px;\n");
      out.write("		}\n");
      out.write("       \n");
      out.write("       .card:hover{ \n");
      out.write("		    transform: translateY(-5%);\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.flight-img {\n");
      out.write("		    height: 11.8rem;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.go-btn {\n");
      out.write("		    background-color: #00ADB5;\n");
      out.write("		    color: white;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.go-btn:hover {\n");
      out.write("		    background-color: #3FC1C9;\n");
      out.write("		    color: white;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.nav-name {\n");
      out.write("			color: #F8F3D4 !important;\n");
      out.write("		}\n");
      out.write("       \n");
      out.write("    </style>\n");
      out.write("	\n");
      out.write("    <!-- Navbar -->\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <a class=\"navbar-brand\" href=\"#\">MotorHub</a>\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("            </button>\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("                <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link active act-cust\" href=\"/Vehicle/dashboard\">Dashboard</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                    	<a class=\"nav-link active\" href=\"/Vehicle/car\">Buy a Car</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                    	<a class=\"nav-link active\" href=\"/Vehicle/bike\">Buy a Bike</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                    	<a class=\"nav-link active\" href=\"/Vehicle/sell\">Sell your vehicle</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                    	<a class=\"nav-link active\" href=\"/Vehicle/orders\">My Orders</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                    	<a class=\"nav-link active nav-name\">");
      out.print( name );
      out.write("</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("                <a href=\"/Vehicle/logout\"><Button class=\"btn btn-danger logout\">Logout</Button></a><br /><br />\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("     </nav>\n");
      out.write("	\n");
      out.write("    <h1 class=\"namehead\">Welcome ");
      out.print( name );
      out.write("</h1>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <!-- Cards -->\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("          <div class=\"card\" style=\"width: 18rem;\">\n");
      out.write("            <img src=\"https://images.unsplash.com/photo-1597404294360-feeeda04612e?ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8Y2FyfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60\" class=\"card-img-top flight-img\" alt=\"...\">\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("              <h5 class=\"card-title\">Cars</h5>\n");
      out.write("              <p class=\"card-text\">View and Order Cars</p>\n");
      out.write("              <a href=\"/Vehicle/car\" class=\"btn go-btn\">Cars</a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("          <div class=\"card\" style=\"width: 18rem;\">\n");
      out.write("            <img src=\"https://images.unsplash.com/photo-1558981403-c5f9899a28bc?ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8YmlrZXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60\" class=\"card-img-top\" alt=\"...\">\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("              <h5 class=\"card-title\">Bikes</h5>\n");
      out.write("              <p class=\"card-text\">View and Order Bikes</p>\n");
      out.write("              <a href=\"/Vehicle/bike\" class=\"btn go-btn\">Bikes</a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("          <div class=\"card\" style=\"width: 18rem;\">\n");
      out.write("            <img src=\"https://images.unsplash.com/photo-1617724054780-ef6bd6b21e17?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Y2FyJTIwb3duZXJ8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60\" class=\"card-img-top\" alt=\"...\">\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("              <h5 class=\"card-title\">Sell</h5>\n");
      out.write("              <p class=\"card-text\">Sell Your Vehicle</p>\n");
      out.write("              <a href=\"/Vehicle/sell\" class=\"btn go-btn\">Sell</a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- Footer -->\n");
      out.write("    <footer class=\"footer\">\n");
      out.write("        <div class=\"footer-item\">\n");
      out.write("        <h1 id=\"ganesh\">Developed by Ganesh Sindagi</h1>\n");
      out.write("        <a href=\"https://www.facebook.com/ganesh.sindagi.3\"><i class=\"social-icon fab fa-facebook-f\"></i></a>\n");
      out.write("        <a href=\"https://twitter.com/GaneshSindagi\"><i class=\"social-icon fab fa-twitter\"></i></a>\n");
      out.write("        <a href=\"https://www.instagram.com/ganesh_sindagi/\"><i class=\"social-icon fab fa-instagram\"></i></a>\n");
      out.write("        <a href = \"mailto:ganeshsindagi7@gmail.com\"><i class=\"social-icon fas fa-envelope\"></i></a>\n");
      out.write("        <p id=\"copyright\">Copyright 2020 MotorHub</p>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("    <!-- jQuery and JS bundle w/ Popper.js -->\n");
      out.write("    <script src=\"https://kit.fontawesome.com/b6a0edf9cb.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    \n");
      out.write("    <!-- JavaScript Bundle with Popper -->\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\" crossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
